# .travis.yml
sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "j_chung@yonsei.ac.kr"
  - git config --global user.email "archi-j"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'

env:
  global:
    secure: "oqwmR4RqvMJTmwYqbrI5QUgf0Wgi36UybQLo/OLoKG7o/c9YzbvUzKiE7Zi4NTwznByUC8Dfxco19xCKuTq5aY05A+yBSjUmU2Ulusa3Z1wKIj/wuT6gXhmtSx37UNAzJQY7W5itUSyW+ZVL2oSEb9WSMyFuutr7J4rGgskNw+Vrq4dBnT6nM6KLcYKxroLsZZvGWkGu/BUokHbGE0Pb+5hP9Mp2tKOp1Iz29b9ZngeZfclOLBy15x29VarCnrvwZYsjc15frDhe3QkhiaPubSzu0t45DcE2xDsChI9HwdrVeJsjKZQ33uEs5Uzi5NAN/PsERZ3VQZb+vTzGp5LgUq1BQi5npRpJOIKuzb/y8LCOQQzrCiAmOroYnS8jR8yfDso65vaU6q6Uud2Omns/hRgFqtG4wzHZg/8jx0J5R+2M0Y68bnYqhPvUkd3wLqkwhYB4+7dfNDfTEmhnuYlWClxfWXksNHzTQPDGc62/uuj0C5ijpiqmFWin9JRxexLJvHUJK/FEV7dLWH3Ep/YliHDnDzptwU2SdvlP5TYgkeLhgoMjC0iG9k8YIvl4UIdhlpX5oXs18Ga45mY1ipSpCD3kwigA5hUfIhPmzTczYkGwSvFomQ9utdQzNjyidBtVIfdS5m/cwFqMJNQvseNf9P0GNl8Kgy0Ou5Cgum18raM="
branches:
  only:
    - master
