title: "Jihoon Chung: Designer, Builder, & Runner"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://archi-j.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
destination: ./builder/
production_url: https://archi-j.github.io/
source_url: https://github.com/archi-j/icon-studio-clone.github.io

safe: False
lsi: False

username: archi-j
repo: icon-studio-clone.github.io
branch: master
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jihoon Chung # add your name
author-img: ../../images/my_pic.jpeg # add your photo
about-author: DESIGNER. <br> BUILDER. <br> & RUNNER. # add description
social-instagram: jihooonchung # add your Instagram handle
social-brunch: likecrazy # add your Facebook handle
social-github: archi-j # add your Github handle
social-linkedin: jihoon-chung # add your Linkedin handle
social-email: j_chung@yonsei.ac.kr # add your Email address

# Disqus
discus-identifier: j-chung-1 # add your discus identifier

# Tracker
analytics: UA-131742616-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jemoji

gems:
  - jekyll-paginate-v2

pagination:
    enabled: true
    per_page: 8
    limit: 0
    sort_field: "date"
    sort_reverse: true

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "README.md", "Rakefile", "Gemfile", "Gemfile.lock", ".travis.yml"]

urls:
    - text: About
      url: /about/
    - text: Grasshopper
      url: /GH/
    - text: Construction 3D Printing
      url: /3DP/
    - text: Computer Vision
      url: /CV/
